Repository likelion-frontendo/likelion-saja, pull requests merged in 2023-03, with the labels that each got.

#27 [코드수정]Button 컴포넌트, LinkButton 컴포넌트 생성
  src/pages/Login/Button.jsx
  src/pages/Login/LinkButton.jsx
Labels: 🎨 html&css

#28 [병합] develop <- feature/jinwoo/login
  src/pages/Login/FormInput.jsx
  src/pages/Login/Login.jsx
  src/pages/index.js
Labels: 🎨 html&css

#32 [병합] #10 Feature/simyumi/mypage
  src/assets/Mypage/bag-frame.svg
  src/assets/Mypage/envelope.svg
  src/assets/Mypage/exclamation-circle.svg
  src/assets/Mypage/gear.svg
  src/assets/Mypage/heart.svg
  src/assets/Mypage/person.svg
  src/assets/Mypage/receipt.svg
  src/assets/Mypage/tag.svg
  src/assets/Mypage/유네찌.png
  src/pages/Mypage/Mypage.jsx
  src/pages/Mypage/SidebarBottom.jsx
  src/pages/Mypage/SidebarTop.jsx
Labels: 🔨코드 수정, 🎨 html&css, 🛠병합

#33 [병합] #2 #3 Header/Footer 마크업 완성
  src/App.jsx
  src/assets/Home/facebook.png
  src/assets/Home/instargram.png
  src/assets/Home/logo.png
  src/assets/Home/naverblog.png
  src/assets/Home/youtube.png
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
Labels: 🎨 html&css, 🛠병합

#36 [병합] #2 #8 Header Footer 마크업 완성
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
Labels: 🎨 html&css, 🛠병합

#38 [병합] css 리팩토링
  src/components/Product.jsx
  src/pages/Home/LineBanner.jsx
  src/pages/Home/MainProduct.jsx
  src/pages/Home/MainStore.jsx
  src/pages/Home/Store.jsx
Labels: 🔨코드 수정, 🛠병합

#41 [병합] index 엔트리 파일 생성 및 코드 리팩토링
  src/App.jsx
  src/components/Product/Product.jsx
  src/components/index.js
  src/pages/Home/Home.jsx
  src/pages/Home/LineBanner.jsx
  src/pages/Home/MainBanner.jsx
  src/pages/Home/MainProduct.jsx
  src/pages/Home/MainStore.jsx
  src/pages/Home/Store.jsx
  src/pages/index.js
Labels: 🔨코드 수정, 🛠병합

#42 [병합] 메인 배너 스와이프 기능 추가
  src/assets/Home/banner01.svg
  src/assets/Home/banner02.svg
  src/assets/Home/banner03.svg
  src/assets/Home/banner04.svg
  src/assets/Home/lineBanner.svg
  src/assets/lineBanner.svg
  src/pages/Home/LineBanner.jsx
  src/pages/Home/MainBanner.jsx
Labels: ✨기능, 🛠병합

#43 [병합] #2 Header min-width 추가
  public/index.html
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
Labels: 🎨 html&css, 🛠병합

#46 [병합] Product props 추가 및 파이어베이스 데이터 가져오기
  .env
  src/components/Header/Header.jsx
  src/components/Product/Product.jsx
  src/components/Product/UseProductList.js
  src/components/index.js
  src/firebase/app.js
  src/pages/Home/LineBanner.jsx
  src/pages/Home/MainBanner.jsx
  src/pages/Home/MainProduct.jsx
Labels: 🔨코드 수정, ✨기능, 🛠병합

#48 [기타] #10 Feature/simyumi/mypage
  src/assets/Mypage/user.png
  src/assets/Mypage/yellowbubble.svg
  src/assets/Mypage/너굴.png
  src/assets/Mypage/너굴.svg
  src/assets/Mypage/매너온도 이미지.svg
  src/assets/Mypage/미첼.png
  src/assets/Mypage/뽀야미.png
  src/assets/Mypage/쭈니.png
  src/pages/Mypage/Compliment.jsx
  src/pages/Mypage/MannerTemperature.jsx
  src/pages/Mypage/Mypage.jsx
  src/pages/Mypage/MypageReview.jsx
  src/pages/Mypage/MypageSection.jsx
  src/pages/Mypage/SectionInfoCount.jsx
  src/pages/Mypage/SectionProfileInfo.jsx
  src/pages/Mypage/SidebarBottom.jsx
  src/pages/Mypage/SidebarTop.jsx
  src/pages/Mypage/index.js
Labels: 🧷기타

#49 [병합] productList 데이터 불러오기 수정
  .env
  src/App.jsx
  src/components/Product/UseProductList.js
Labels: 🔨코드 수정, 🛠병합

#50 [병합] #4 mainProduct 함수 리펙토링
  src/components/Product/UseProductList.jsx
  src/components/Product/UseProducts.jsx
  src/components/index.js
  src/pages/Home/MainProduct.jsx
Labels: ✨기능, 🛠병합

#51 [병합] useState => useRecoilState로 변경 했습니다.
  src/components/Product/UseProductList.jsx
  src/components/Product/UseProducts.jsx
Labels: ✨기능, 🛠병합

#53 [스타일] #11 Feature/simyumi/post
  src/App.jsx
  src/assets/Post/camera-fill.svg
  src/pages/Post/Post.jsx
  src/pages/Post/PostImage.jsx
  src/pages/Post/PostSection.jsx
  src/pages/Post/PostText.jsx
  src/pages/Post/index.jsx
Labels: 🔨코드 수정, 🎨 html&css, 🛠병합

#54 [병합] 코드 리펙토링 및 모달창 컴포넌트 생성
  src/pages/Login/LinkButton.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginModal.jsx
  src/pages/Login/index.js
Labels: 🔨코드 수정, 🎨 html&css, ✨기능, 🧷기타

#55 [병합] 상품을 보여주는 컴포넌트 완성
  src/components/Product/UseProductList.jsx
  src/pages/Home/MainProduct.jsx
Labels: ✨기능, 🛠병합

#56 [병합] 파이어베이스에서 Store 데이터 불러오기
  src/pages/Home/MainStore.jsx
  src/pages/Home/Store.jsx
  src/pages/Home/UserStoreList.jsx
  src/pages/Home/index.js
Labels: ✨기능, 🛠병합

#57 [스타일] #11 Feature/simyumi/post 마크업 완료
  src/App.jsx
  src/assets/Post/right.svg
  src/pages/Post/PlaceSearchBox.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostImage.jsx
  src/pages/Post/PostSection.jsx
  src/pages/Post/PostText.jsx
  src/pages/Post/index.jsx
  src/pages/index.js
Labels: 🔨코드 수정, 🎨 html&css, 🛠병합

#61 [병합] 상품 상세페이지 마크업 완료
  src/App.jsx
  src/components/Header/Header.jsx
  src/components/Product/Product.jsx
  src/pages/Home/UseStores.jsx
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductDetailBody.jsx
  src/pages/ProductDetail/UseProductDetail.jsx
  src/pages/ProductDetail/index.js
  src/pages/index.js
Labels: 🎨 html&css, 🛠병합

#64 [기능] # 11 Feature/simyumi/post
  src/pages/Post/PlaceSearchBox.jsx
  src/pages/Post/PostImage.jsx
Labels: 🔨코드 수정, 🎨 html&css, ✨기능

#65 [병합] 가게 필터 기능 추가
  src/pages/Home/MainStore.jsx
  src/pages/Home/UseStoreList.jsx
  src/pages/Home/UseStoresType.jsx
Labels: ✨기능, 🛠병합

#66 [병합] 헤더,푸터, 메인페이지 코드 정리
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Product/Product.jsx
  src/components/Product/UseProducts.jsx
  src/components/index.js
  src/pages/Home/LineBanner.jsx
  src/pages/Home/MainBanner.jsx
  src/pages/Home/MainProduct.jsx
  src/pages/Home/MainStore.jsx
  src/pages/Home/Store.jsx
  src/pages/Home/UseStoreList.jsx
  src/pages/Home/UseStores.jsx
  src/pages/Home/UseStoresType.jsx
  src/pages/Home/index.js
Labels: 🔨코드 수정, 🛠병합

#69 [기능] #67 Feature/simyumi/post
  src/pages/Post/PostText.jsx
Labels: 🔨코드 수정, ✨기능

#71 [병합] 상품상세페이지 고유 상품들과 연결
  src/App.jsx
  src/components/Product/Product.jsx
  src/components/Product/UseProductList.jsx
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/UseProductDetail.jsx
Labels: ✨기능, 🛠병합

#73 [병합] interest 삭제, Product와 Store firebase 코드 수정
  src/components/Product/Product.jsx
  src/components/Product/UseProductList.jsx
  src/components/Product/UseProducts.jsx
  src/pages/Home/UseStores.jsx
  src/pages/ProductDetail/ProductDetailBody.jsx
  src/pages/ProductDetail/UseProductDetail.jsx
Labels: 🔨코드 수정, 🛠병합

#75 [기타] #74 Feature/simyumi/post
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Mypage/Mypage.jsx
  src/pages/Post/PlaceSearchBox.jsx
  src/pages/Post/Post.jsx
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/Register/Register.jsx
Labels: 🔨코드 수정, 🧷기타

#77 [병합] 상품상세페이지 및 인기매물페이지 추가
  src/App.jsx
  src/assets/Logo/raccoon.gif
  src/components/Header/Header.jsx
  src/components/Product/Product.jsx
  src/components/Product/UseProductList.jsx
  src/components/Product/UseProducts.jsx
  src/pages/Home/MainProduct.jsx
  src/pages/Home/UseStoreList.jsx
  src/pages/PopularProduct/PopularProduct.jsx
  src/pages/PopularProduct/PopularProductBody.jsx
  src/pages/PopularProduct/index.js
  src/pages/ProductDetail/ProductDetailBody.jsx
  src/pages/index.js
Labels: 🎨 html&css, ✨기능, 🛠병합

#80 [기능] #67 Feature/simyumi/post
  src/pages/Mypage/SectionProfileInfo.jsx
  src/pages/Mypage/SidebarTop.jsx
Labels: 🔨코드 수정, ✨기능

#81 [병합] post 페이지 리팩토링
  src/pages/Post/PlaceSearchBox.jsx
  src/pages/Post/PostText.jsx
Labels: 🔨코드 수정, ✨기능

#82 [병합] 메인페이지 메인 광고, 라인 광고 이미지 변경
  src/assets/Home/banner01.svg
  src/assets/Home/banner02.svg
  src/assets/Home/banner03.svg
  src/assets/Home/banner04.svg
  src/assets/Home/lineBanner.png
  src/assets/Home/lineBanner.svg
  src/assets/Home/mainBanner1.png
  src/assets/Home/mainBanner2.png
  src/assets/Home/mainBanner3.png
  src/assets/Home/mainBanner4.png
  src/components/Product/UseProductList.jsx
  src/components/Product/UseProducts.jsx
  src/pages/Home/LineBanner.jsx
  src/pages/Home/MainBanner.jsx
  src/pages/Home/UseStoreList.jsx
  src/pages/ProductDetail/index.js
Labels: 🎨 html&css, 🛠병합

#84 [병합] 상품상세페이지 user 프로필, 아이디, 장소 마크업
  src/pages/ProductDetail/ProductDetailBody.jsx
Labels: 🎨 html&css, 🛠병합

#85 [병합] 로그인 userId값 받아오기
  src/pages/Post/PlaceSearchBox.jsx
Labels: 🔨코드 수정, ✨기능

#86 [기타] #67 Feature/simyumi/post
  src/components/UpButton/UpButton.jsx
  src/pages/Post/PlaceSearchBox.jsx
  src/pages/Post/PostImage.jsx
  src/pages/Post/PostText.jsx
Labels: 🔨코드 수정

#87 [병합] post 페이지 코드 수정 및 리팩토링
  src/pages/Post/PostImage.jsx
Labels: 🔨코드 수정, ✨기능

#88 [기타] Header 버튼 스타일 수정
  src/components/Header/Header.jsx
  src/pages/PopularProduct/PopularProduct.jsx
Labels: 🧷기타

#89 [기능] Feature/simyumi/post
  src/pages/Mypage/MannerTemperature.jsx
  src/pages/Post/PlaceSearchBox.jsx
Labels: ✨기능

#90 [병합] 매물 개수 증가
  src/components/Product/UseProducts.jsx
Labels: 🛠병합, 🧷기타

#94 [병합] 상품 상세 페이지 데이터 불러오기 수정
  src/components/Product/UseProducts.jsx
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/UseProductDetail.jsx
Labels: 🔨코드 수정, 🐞버그, 🛠병합
